import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { Footer, Navbar, ThemeProvider } from "@/components/comps"
import "./globals.css"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

interface PageProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: {
    default: "Default Title",
    template: "%s | Flow Jobs"
  },
  description: "Generated by create next app"
}

export default function RootLayout(props: PageProps) {
  const { children } = props

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
